"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Send } from "lucide-react";
import { useWallet } from "./wallet-provider";
import { useTransactions } from "./transaction-provider";
import { submitContract, waitForFinalized, executionSucceeded } from "@/lib/contract";

export function DeliveryForm({ workId, criteria, repository }: { workId: number; criteria: string[]; repository: string }) {
  const wallet = useWallet(); const txs = useTransactions(); const router = useRouter(); const [evidence, setEvidence] = useState(criteria.map(() => "")); const [status, setStatus] = useState(""); const [busy, setBusy] = useState(false);
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!wallet.connected) return void wallet.connect(); if (!wallet.correctNetwork) return void wallet.switchNetwork(); if (!wallet.client) return; const form = new FormData(event.currentTarget); const id = txs.track(`Submit revision for work #${workId}`); setBusy(true);
    try { const revision = String(form.get("revision")).trim(); if (!/^[0-9a-f]{40}$/i.test(revision)) throw new Error("Use a full 40-character commit SHA."); const artifactUrl = String(form.get("artifactUrl")).trim(); if (!artifactUrl.startsWith(`${repository}/commit/`)) throw new Error("Artifact URL must be a commit page in the frozen repository."); if (evidence.some(value => !value.trim())) throw new Error("Map public evidence to every criterion."); txs.update(id,{stage:"signature"}); setStatus("Awaiting wallet approval…"); const hash=String(await submitContract(wallet.client,"deliver_revision",[workId,revision,artifactUrl,String(form.get("checkUrl")||"").trim(),JSON.stringify(evidence)])); txs.update(id,{hash,stage:"submitted"}); setStatus("Submission is in consensus…"); const receipt=await waitForFinalized(wallet.client,hash,stage => txs.update(id,{stage})); if(!executionSucceeded(receipt)) throw new Error("Submission finalized without successful execution."); txs.update(id,{stage:"finalized"}); router.push(`/work/${workId}`); router.refresh(); }
    catch(cause){const message=cause instanceof Error?cause.message:"Submission failed.";setStatus(message);txs.update(id,{stage:"failed",error:message});} finally{setBusy(false);} };
  return <form className="delivery-form" onSubmit={submit}><label>Full commit SHA<input name="revision" placeholder="40-character immutable revision" required/></label><label>Canonical commit URL<input name="artifactUrl" type="url" placeholder={`${repository}/commit/…`} required/></label><label>Public check URL <small>optional</small><input name="checkUrl" type="url" placeholder="Public CI run tied to this revision"/></label><div className="evidence-mapping"><div className="kicker">Criterion evidence map</div>{criteria.map((criterion,index)=><label key={criterion}><span><b>{index+1}</b>{criterion}</span><textarea rows={3} value={evidence[index]} onChange={event=>setEvidence(v=>v.map((item,i)=>i===index?event.target.value:item))} placeholder="Point validators to the relevant file, diff, test, or public check…" required/></label>)}</div><button className="button primary" disabled={busy}>{busy?"Following finality…":<>Submit immutable revision <Send size={16}/></>}</button>{status&&<p role="status" className="form-status">{status}</p>}</form>;
}
